package randomlistchunks;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.swing.JOptionPane;


/**
 * Get the prime numbers from a random list using multiple threads that receive chunks from the list
 * @author btesila
 *
 */
public class Test {
	
	
	public static boolean isPrime(int number){
		for (int i = 2; i <= number/2; i++)
            if (number % i == 0)
                return false;

        return true;
	}


	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		Random randomGenerator = new Random();
		List<Integer> randomList = new ArrayList<>();
		
		//This is the correct list of prime numbers
		List<Integer> correctPrimeList = new ArrayList<>();
		
		//This is the list of prime numbers generated by the threads
		List<Integer> primeList = new ArrayList<>();
		
		for(int i=0; i<100; i++){
			randomList.add(i);
			if(isPrime(i)){
				correctPrimeList.add(i);
			}
		}
		
		List<Thread> threadList = new ArrayList<>();
		
		int numberOfThreads = Integer.parseInt(JOptionPane.showInputDialog("Give the number of threads"));
		System.out.println("Number of threads "+numberOfThreads);
		
		int chunkSize = randomList.size()/numberOfThreads;
		int lastChunkSize = chunkSize+randomList.size()%numberOfThreads;
		
		System.out.println("Chunk size "+chunkSize);
		System.out.println("Last chunk size "+lastChunkSize);
		
		for(int i=0; i<numberOfThreads; i++){
			int startOffset = i*chunkSize+1;
			int endOffset = (i+1)*chunkSize;
			
			if(i == 0){
				startOffset = 0;
			}
			
			if(i == numberOfThreads-1){
				endOffset = startOffset+lastChunkSize-1;
			}
			Thread threadToBeAdded = new Thread(new ListThread(randomList, primeList, startOffset, endOffset));
			System.out.println("Thread "+ListThread.currentID+" starts from "+startOffset+" and ends at "+endOffset);
			threadList.add(threadToBeAdded);
			threadToBeAdded.start();
		}
		
		//In order to check the result, I need to wait for all the threads to finish their task
		 for (Thread thread : threadList){
	            try {
	                thread.join();
	            } catch (InterruptedException e) {
	                e.printStackTrace();
	            }
		 }
		 
		 System.out.println("Prime number list "+primeList);
		 
		 System.out.println("The result is "+(primeList.size()==correctPrimeList.size() && primeList.containsAll(correctPrimeList)));
	}
	
	

}
