-- MySQL Script generated by MySQL Workbench
-- 05/27/14 17:57:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema final_project_federated_search
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `final_project_federated_search` ;
CREATE SCHEMA IF NOT EXISTS `final_project_federated_search` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema proiect_federated_search
-- -----------------------------------------------------
USE `final_project_federated_search` ;

-- -----------------------------------------------------
-- Table `final_project_federated_search`.`queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`queries` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`queries` (
  `id_query` INT NOT NULL AUTO_INCREMENT,
  `query` VARCHAR(255) NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id_query`),
  UNIQUE INDEX `id_query_UNIQUE` (`id_query` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`actors` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`actors` (
  `id_actor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id_actor`),
  UNIQUE INDEX `id_actor_UNIQUE` (`id_actor` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`genres` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`genres` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genre`),
  UNIQUE INDEX `id_genre_UNIQUE` (`id_genre` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`tv_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`tv_series` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`tv_series` (
  `id_tv_series` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `year` INT NULL,
  `country` VARCHAR(100) NULL,
  `url` VARCHAR(255) NULL,
  `overview` TEXT NULL,
  `poster` VARCHAR(255) NULL,
  `status` VARCHAR(255) NULL,
  `imdb_id` VARCHAR(100) NULL,
  `tvrage_id` VARCHAR(100) NULL,
  `id_query` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_tv_series`),
  UNIQUE INDEX `id_tv_series_UNIQUE` (`id_tv_series` ASC),
  INDEX `fk_tv_series_queries_idx` (`id_query` ASC),
  CONSTRAINT `fk_tv_series_queries`
    FOREIGN KEY (`id_query`)
    REFERENCES `final_project_federated_search`.`queries` (`id_query`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`episodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`episodes` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`episodes` (
  `id_episode` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `number` INT NULL,
  `season` INT NULL,
  `url` VARCHAR(255) NULL,
  `id_tv_series` INT NOT NULL,
  PRIMARY KEY (`id_episode`),
  UNIQUE INDEX `id_episode_UNIQUE` (`id_episode` ASC),
  INDEX `fk_episodes_tv_series1_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_episodes_tv_series1`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `final_project_federated_search`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`tv_series_has_actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`tv_series_has_actors` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`tv_series_has_actors` (
  `id_tv_series` INT NOT NULL,
  `id_actor` INT NOT NULL,
  PRIMARY KEY (`id_tv_series`, `id_actor`),
  INDEX `fk_tv_series_has_actors_actors1_idx` (`id_actor` ASC),
  INDEX `fk_tv_series_has_actors_tv_series1_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_tv_series_has_actors_tv_series1`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `final_project_federated_search`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tv_series_has_actors_actors1`
    FOREIGN KEY (`id_actor`)
    REFERENCES `final_project_federated_search`.`actors` (`id_actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `final_project_federated_search`.`tv_series_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `final_project_federated_search`.`tv_series_has_genres` ;

CREATE TABLE IF NOT EXISTS `final_project_federated_search`.`tv_series_has_genres` (
  `id_tv_series` INT NOT NULL,
  `id_genre` INT NOT NULL,
  PRIMARY KEY (`id_tv_series`, `id_genre`),
  INDEX `fk_tv_series_has_genres_genres1_idx` (`id_genre` ASC),
  INDEX `fk_tv_series_has_genres_tv_series1_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_tv_series_has_genres_tv_series1`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `final_project_federated_search`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tv_series_has_genres_genres1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `final_project_federated_search`.`genres` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE `final_project_federated_search`.`tv_series` 
DROP FOREIGN KEY `fk_tv_series_queries`;
ALTER TABLE `final_project_federated_search`.`tv_series` 
CHANGE COLUMN `id_query` `id_query` INT(11) NULL DEFAULT '0' ;
ALTER TABLE `final_project_federated_search`.`tv_series` 
ADD CONSTRAINT `fk_tv_series_queries`
  FOREIGN KEY (`id_query`)
  REFERENCES `final_project_federated_search`.`queries` (`id_query`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  ALTER TABLE `final_project_federated_search`.`episodes` 
DROP FOREIGN KEY `fk_episodes_tv_series1`;
ALTER TABLE `final_project_federated_search`.`episodes` 
CHANGE COLUMN `id_tv_series` `id_tv_series` INT(11) NULL DEFAULT 0 ;
ALTER TABLE `final_project_federated_search`.`episodes` 
ADD CONSTRAINT `fk_episodes_tv_series1`
  FOREIGN KEY (`id_tv_series`)
  REFERENCES `final_project_federated_search`.`tv_series` (`id_tv_series`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
  
ALTER TABLE `final_project_federated_search`.`actors` 
DROP INDEX `name_UNIQUE` ;

ALTER TABLE `final_project_federated_search`.`genres` 
DROP INDEX `name_UNIQUE` ;

  
  
  
