-- MySQL Script generated by MySQL Workbench
-- 05/22/14 18:30:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imdbsearch
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `imdbsearch` ;
CREATE SCHEMA IF NOT EXISTS `imdbsearch` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `imdbsearch` ;

-- -----------------------------------------------------
-- Table `imdbsearch`.`actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`actors` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`actors` (
  `id_actor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_actor`),
  UNIQUE INDEX `idactor_UNIQUE` (`id_actor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdbsearch`.`tv_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`tv_series` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`tv_series` (
  `id_tv_series` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `year` INT NULL,
  `url` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `tv_seriescol` VARCHAR(45) NULL,
  `overview` VARCHAR(255) NULL,
  `status` VARCHAR(45) NULL,
  `network` VARCHAR(45) NULL,
  `poster` VARCHAR(100) NULL,
  `air_day` VARCHAR(45) NULL,
  `air_time` VARCHAR(45) NULL,
  `imdb_id` VARCHAR(45) NULL,
  `tvrage_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tv_series`),
  UNIQUE INDEX `idtv_series_UNIQUE` (`id_tv_series` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdbsearch`.`episodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`episodes` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`episodes` (
  `id_episode` INT NOT NULL AUTO_INCREMENT,
  `plays` INT NULL,
  `season` INT NULL,
  `number` INT NULL,
  `title` VARCHAR(100) NULL,
  `url` VARCHAR(100) NULL,
  `id_tv_series` INT NOT NULL,
  PRIMARY KEY (`id_episode`),
  UNIQUE INDEX `id_episode_UNIQUE` (`id_episode` ASC),
  INDEX `fk_episodes_tv_series1_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_episodes_tv_series1`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `imdbsearch`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdbsearch`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`genres` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`genres` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genre`),
  UNIQUE INDEX `id_genre_UNIQUE` (`id_genre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdbsearch`.`tv_series_has_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`tv_series_has_genres` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`tv_series_has_genres` (
  `id_tv_series` INT NOT NULL,
  `id_genre` INT NOT NULL,
  PRIMARY KEY (`id_tv_series`, `id_genre`),
  INDEX `fk_tv_series_has_genres_genres1_idx` (`id_genre` ASC),
  INDEX `fk_tv_series_has_genres_tv_series_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_tv_series_has_genres_tv_series`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `imdbsearch`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tv_series_has_genres_genres1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `imdbsearch`.`genres` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imdbsearch`.`tv_series_has_actors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `imdbsearch`.`tv_series_has_actors` ;

CREATE TABLE IF NOT EXISTS `imdbsearch`.`tv_series_has_actors` (
  `id_tv_series` INT NOT NULL,
  `id_actor` INT NOT NULL,
  PRIMARY KEY (`id_tv_series`, `id_actor`),
  INDEX `fk_tv_series_has_actors_actors1_idx` (`id_actor` ASC),
  INDEX `fk_tv_series_has_actors_tv_series1_idx` (`id_tv_series` ASC),
  CONSTRAINT `fk_tv_series_has_actors_tv_series1`
    FOREIGN KEY (`id_tv_series`)
    REFERENCES `imdbsearch`.`tv_series` (`id_tv_series`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tv_series_has_actors_actors1`
    FOREIGN KEY (`id_actor`)
    REFERENCES `imdbsearch`.`actors` (`id_actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


ALTER TABLE `imdbsearch`.`tv_series` 
CHANGE COLUMN `title` `title` VARCHAR(100) NOT NULL ;