-- MySQL Script generated by MySQL Workbench
-- 05/12/14 14:50:32
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Judet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Judet` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Judet` (
  `ID` INT NOT NULL,
  `Nume` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oras` (
  `ID` INT NOT NULL,
  `Nume` VARCHAR(45) NOT NULL,
  `Judet_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Oras_Judet1_idx` (`Judet_ID` ASC),
  CONSTRAINT `fk_Oras_Judet1`
    FOREIGN KEY (`Judet_ID`)
    REFERENCES `mydb`.`Judet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ID` INT NOT NULL,
  `Nume` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(120) NULL,
  `Oras_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Client_Oras1_idx` (`Oras_ID` ASC),
  CONSTRAINT `fk_Client_Oras1`
    FOREIGN KEY (`Oras_ID`)
    REFERENCES `mydb`.`Oras` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film` (
  `ID` INT NOT NULL,
  `Titlu` VARCHAR(45) NOT NULL,
  `Descriere` VARCHAR(120) NULL,
  `Durata` TIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `ID` INT NOT NULL,
  `Denumire` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Film_has_Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Film_has_Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Film_has_Categorie` (
  `Film_ID` INT NOT NULL,
  `Categorie_ID` INT NOT NULL,
  PRIMARY KEY (`Film_ID`, `Categorie_ID`),
  INDEX `fk_Film_has_Categorie_Categorie1_idx` (`Categorie_ID` ASC),
  INDEX `fk_Film_has_Categorie_Film_idx` (`Film_ID` ASC),
  CONSTRAINT `fk_Film_has_Categorie_Film`
    FOREIGN KEY (`Film_ID`)
    REFERENCES `mydb`.`Film` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Film_has_Categorie_Categorie1`
    FOREIGN KEY (`Categorie_ID`)
    REFERENCES `mydb`.`Categorie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DVD` (
  `COD` INT NOT NULL,
  `Tarif` DECIMAL(10,0) NOT NULL,
  `NumarExemplare` INT NOT NULL,
  `Film_ID` INT NOT NULL,
  PRIMARY KEY (`COD`),
  INDEX `fk_DVD_Film1_idx` (`Film_ID` ASC),
  CONSTRAINT `fk_DVD_Film1`
    FOREIGN KEY (`Film_ID`)
    REFERENCES `mydb`.`Film` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bon_Inchiriere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bon_Inchiriere` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bon_Inchiriere` (
  `ID` INT NOT NULL,
  `Data` DATETIME NULL,
  `Client_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Bon_Inchiriere_Client1_idx` (`Client_ID` ASC),
  CONSTRAINT `fk_Bon_Inchiriere_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bon_Inchiriere_has_DVD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bon_Inchiriere_has_DVD` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bon_Inchiriere_has_DVD` (
  `Bon_Inchiriere_ID` INT NOT NULL,
  `DVD_COD` INT NOT NULL,
  PRIMARY KEY (`Bon_Inchiriere_ID`, `DVD_COD`),
  INDEX `fk_Bon_Inchiriere_has_DVD_DVD1_idx` (`DVD_COD` ASC),
  INDEX `fk_Bon_Inchiriere_has_DVD_Bon_Inchiriere1_idx` (`Bon_Inchiriere_ID` ASC),
  CONSTRAINT `fk_Bon_Inchiriere_has_DVD_Bon_Inchiriere1`
    FOREIGN KEY (`Bon_Inchiriere_ID`)
    REFERENCES `mydb`.`Bon_Inchiriere` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bon_Inchiriere_has_DVD_DVD1`
    FOREIGN KEY (`DVD_COD`)
    REFERENCES `mydb`.`DVD` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
